default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['RUBYTIFY_DATABASE_HOSTNAME'] || 'localhost' %>
  username: <%= ENV['RUBYTIFY_DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['RUBYTIFY_DATABASE_PASSWORD'] %>
  pool: <%= ENV['RUBYTIFY_DATABASE_POOL'] || 10 %>

development:
  <<: *default
  database: rubytify_development

test:
  <<: *default
  database: rubytify_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
